window.BRIGHTMIND_DATA = {
  "generatedAt": "2026-06-11T10:35:31.553Z",
  "articles": [
    {
      "id": 1,
      "slug": "what-is-photosynthesis",
      "title": "What is Photosynthesis? Complete Guide for Students",
      "title_hi": "प्रकाश संश्लेषण क्या है? छात्रों के लिए सम्पूर्ण गाइड",
      "category": "school",
      "emoji": "🌿",
      "excerpt": "Learn how plants make their own food using sunlight, water and carbon dioxide. Complete explanation with diagrams and examples for Class 9-10 students.",
      "author": "Dr. Priya Sharma",
      "date": "2024-01-15",
      "readTime": 8,
      "featured": true,
      "tags": [
        "science",
        "biology",
        "class-9",
        "class-10",
        "photosynthesis"
      ],
      "content": "<h2>What is Photosynthesis?</h2><p>Photosynthesis is the process by which <strong>green plants, algae, and some bacteria</strong> convert light energy (usually from the sun) into chemical energy stored in glucose. It is one of the most important biological processes on Earth.</p><div class='highlight-box'><strong>Simple Definition:</strong> Photosynthesis = Sun + Water + CO₂ → Glucose + Oxygen</div><h2>The Chemical Equation</h2><p>The overall equation for photosynthesis is:</p><div class='fact-box'><strong>6CO₂ + 6H₂O + Light Energy → C₆H₁₂O₆ + 6O₂</strong><br><br>This means: 6 molecules of carbon dioxide + 6 molecules of water + light energy produces 1 molecule of glucose + 6 molecules of oxygen.</div><h2>Where Does Photosynthesis Occur?</h2><p>Photosynthesis occurs in the <strong>chloroplasts</strong> of plant cells. Chloroplasts contain a green pigment called <strong>chlorophyll</strong>, which absorbs light energy and gives plants their green color.</p><ul><li><strong>Chloroplast:</strong> The organelle where photosynthesis takes place</li><li><strong>Chlorophyll:</strong> Green pigment that captures light energy</li><li><strong>Thylakoids:</strong> Membrane structures inside chloroplasts where light reactions occur</li><li><strong>Stroma:</strong> Fluid-filled space where the Calvin cycle occurs</li></ul><h2>Two Stages of Photosynthesis</h2><h3>Stage 1: Light-Dependent Reactions</h3><p>These reactions occur in the <strong>thylakoid membranes</strong> and require direct sunlight. During this stage:</p><ul><li>Light energy is absorbed by chlorophyll</li><li>Water molecules are split (photolysis)</li><li>Oxygen is released as a byproduct</li><li>ATP and NADPH are produced for use in Stage 2</li></ul><h3>Stage 2: The Calvin Cycle (Light-Independent Reactions)</h3><p>These reactions occur in the <strong>stroma</strong> of the chloroplast. They do NOT directly require light but use the ATP and NADPH from Stage 1:</p><ul><li>CO₂ is fixed (converted) into organic compounds</li><li>Glucose (C₆H₁₂O₆) is produced</li><li>This glucose is used by the plant for energy and growth</li></ul><h2>Factors Affecting Photosynthesis</h2><table><tr><th>Factor</th><th>Effect on Photosynthesis</th></tr><tr><td>Light Intensity</td><td>Higher light = more photosynthesis (up to a limit)</td></tr><tr><td>CO₂ Concentration</td><td>More CO₂ = faster rate of photosynthesis</td></tr><tr><td>Temperature</td><td>Optimal at 25-35°C; too high or low slows it</td></tr><tr><td>Water Availability</td><td>Water shortage stops photosynthesis</td></tr><tr><td>Chlorophyll Amount</td><td>More chlorophyll = more light absorbed</td></tr></table><h2>Why is Photosynthesis Important?</h2><ul><li>🌬️ <strong>Oxygen Production:</strong> All the oxygen in our atmosphere comes from photosynthesis</li><li>🍎 <strong>Food Production:</strong> It is the base of all food chains on Earth</li><li>☁️ <strong>Carbon Cycle:</strong> Helps regulate CO₂ levels in the atmosphere</li><li>⚡ <strong>Energy Flow:</strong> Solar energy is converted to chemical energy for all living things</li></ul><h2>Key Terms to Remember</h2><ul><li><strong>Autotrophs:</strong> Organisms that make their own food (plants)</li><li><strong>Heterotrophs:</strong> Organisms that depend on others for food (animals)</li><li><strong>Photoautotrophs:</strong> Organisms that use light to make food</li></ul><div class='highlight-box'><strong>Remember for Exams:</strong> Photosynthesis happens in CHLOROPLASTS. The green color of plants is due to CHLOROPHYLL. Oxygen is a BYPRODUCT of photosynthesis.</div>",
      "content_hi": "<h2>प्रकाश संश्लेषण क्या है?</h2><p>प्रकाश संश्लेषण वह प्रक्रिया है जिसमें <strong>हरे पौधे, शैवाल और कुछ जीवाणु</strong> सूर्य के प्रकाश की ऊर्जा को ग्लूकोज में संग्रहित रासायनिक ऊर्जा में परिवर्तित करते हैं।</p><div class='highlight-box'><strong>सरल परिभाषा:</strong> प्रकाश + जल + CO₂ → ग्लूकोज + ऑक्सीजन</div><h2>रासायनिक समीकरण</h2><div class='fact-box'><strong>6CO₂ + 6H₂O + प्रकाश ऊर्जा → C₆H₁₂O₆ + 6O₂</strong></div><h2>प्रकाश संश्लेषण कहाँ होता है?</h2><p>प्रकाश संश्लेषण पौधों की कोशिकाओं के <strong>क्लोरोप्लास्ट</strong> में होता है। क्लोरोप्लास्ट में <strong>क्लोरोफिल</strong> नामक हरा वर्णक होता है।</p><h2>परीक्षा के लिए याद रखें</h2><ul><li>प्रकाश संश्लेषण क्लोरोप्लास्ट में होता है</li><li>पौधों का हरा रंग क्लोरोफिल के कारण होता है</li><li>ऑक्सीजन इस प्रक्रिया का उपोत्पाद है</li></ul>"
    },
    {
      "id": 2,
      "slug": "newtons-laws-of-motion",
      "title": "Newton's Three Laws of Motion - Explained with Examples",
      "title_hi": "न्यूटन के गति के तीन नियम - उदाहरण सहित",
      "category": "school",
      "emoji": "🍎",
      "excerpt": "Understand Newton's 3 Laws of Motion with real-world examples. Perfect for Class 9 Physics students preparing for board exams.",
      "author": "Prof. Rajesh Kumar",
      "date": "2024-01-20",
      "readTime": 7,
      "featured": false,
      "tags": [
        "physics",
        "science",
        "class-9",
        "newton",
        "motion"
      ],
      "content": "<h2>Who was Isaac Newton?</h2><p>Sir Isaac Newton (1643-1727) was an English mathematician and physicist. In 1687, he published his famous book <em>Principia Mathematica</em>, which contains his three laws of motion that form the foundation of classical mechanics.</p><h2>Newton's First Law of Motion (Law of Inertia)</h2><div class='highlight-box'><strong>Statement:</strong> An object at rest stays at rest, and an object in motion stays in motion at constant velocity, unless acted upon by an external unbalanced force.</div><h3>Key Concept: Inertia</h3><p><strong>Inertia</strong> is the tendency of an object to resist changes in its state of motion. Heavier objects have more inertia than lighter objects.</p><p><strong>Real-life Examples:</strong></p><ul><li>🚗 When a car suddenly brakes, passengers jerk forward — their bodies want to keep moving</li><li>📚 A book on a table stays there until you push it</li><li>🏈 A football keeps rolling until friction stops it</li></ul><h2>Newton's Second Law of Motion</h2><div class='highlight-box'><strong>Statement:</strong> The acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass.</div><div class='fact-box'><strong>Formula: F = ma</strong><br><br>Where: F = Force (in Newtons), m = mass (in kg), a = acceleration (in m/s²)</div><h3>Understanding F = ma</h3><ul><li>If you double the force → acceleration doubles</li><li>If you double the mass → acceleration halves</li></ul><p><strong>Example:</strong> If you push a 5 kg box with 20 N force:<br>Acceleration = F/m = 20/5 = <strong>4 m/s²</strong></p><table><tr><th>Force (N)</th><th>Mass (kg)</th><th>Acceleration (m/s²)</th></tr><tr><td>10</td><td>2</td><td>5</td></tr><tr><td>20</td><td>4</td><td>5</td></tr><tr><td>30</td><td>5</td><td>6</td></tr></table><h2>Newton's Third Law of Motion</h2><div class='highlight-box'><strong>Statement:</strong> For every action, there is an equal and opposite reaction.</div><p><strong>Real-life Examples:</strong></p><ul><li>🚀 <strong>Rocket Propulsion:</strong> Gas expelled downward (action) → rocket moves upward (reaction)</li><li>🏊 <strong>Swimming:</strong> Hands push water backward (action) → body moves forward (reaction)</li><li>🔫 <strong>Gun Recoil:</strong> Bullet fires forward (action) → gun kicks backward (reaction)</li><li>🐟 <strong>Fish Swimming:</strong> Fins push water back → fish moves forward</li></ul><h2>Quick Comparison Table</h2><table><tr><th>Law</th><th>Key Word</th><th>Formula</th></tr><tr><td>First Law</td><td>Inertia</td><td>F = 0 → a = 0</td></tr><tr><td>Second Law</td><td>Force</td><td>F = ma</td></tr><tr><td>Third Law</td><td>Action-Reaction</td><td>F₁ = -F₂</td></tr></table><div class='highlight-box'><strong>Exam Tip:</strong> Always remember — Third Law forces act on DIFFERENT objects, not the same object. Action and reaction are always equal in magnitude but opposite in direction.</div>",
      "content_hi": "<h2>न्यूटन के गति के नियम</h2><p>सर आइज़क न्यूटन ने 1687 में गति के तीन नियम दिए जो आज भी भौतिकी की नींव हैं।</p><h2>पहला नियम (जड़त्व का नियम)</h2><div class='highlight-box'><strong>कथन:</strong> कोई वस्तु तब तक अपनी स्थिति नहीं बदलती जब तक उस पर कोई बाहरी बल न लगे।</div><h2>दूसरा नियम</h2><div class='fact-box'><strong>सूत्र: F = ma</strong><br>जहाँ F = बल, m = द्रव्यमान, a = त्वरण</div><h2>तीसरा नियम</h2><div class='highlight-box'><strong>कथन:</strong> प्रत्येक क्रिया की समान और विपरीत प्रतिक्रिया होती है।</div>"
    },
    {
      "id": 3,
      "slug": "english-grammar-tenses",
      "title": "English Grammar: All 12 Tenses Explained with Examples",
      "title_hi": "अंग्रेजी व्याकरण: सभी 12 काल उदाहरण सहित",
      "category": "school",
      "emoji": "📚",
      "excerpt": "Complete guide to all 12 English tenses with rules, structures, and examples. Essential for school exams and competitive tests.",
      "author": "Ms. Sunita Verma",
      "date": "2024-02-01",
      "readTime": 10,
      "featured": false,
      "tags": [
        "english",
        "grammar",
        "tenses",
        "school",
        "language"
      ],
      "content": "<h2>Introduction to Tenses</h2><p>Tenses indicate the <strong>time of an action</strong> in a sentence. There are three main tenses in English: <strong>Present, Past, and Future</strong>. Each has four forms, making a total of <strong>12 tenses</strong>.</p><h2>Present Tense (4 Types)</h2><h3>1. Simple Present Tense</h3><div class='highlight-box'><strong>Structure:</strong> Subject + V1 (s/es for he/she/it)<br><strong>Example:</strong> She <em>reads</em> books every day.</div><p><strong>Uses:</strong> Habits, general truths, facts</p><h3>2. Present Continuous Tense</h3><div class='highlight-box'><strong>Structure:</strong> Subject + is/am/are + V-ing<br><strong>Example:</strong> She <em>is reading</em> a book right now.</div><p><strong>Uses:</strong> Actions happening right now</p><h3>3. Present Perfect Tense</h3><div class='highlight-box'><strong>Structure:</strong> Subject + has/have + V3<br><strong>Example:</strong> She <em>has read</em> this book before.</div><h3>4. Present Perfect Continuous</h3><div class='highlight-box'><strong>Structure:</strong> Subject + has/have + been + V-ing<br><strong>Example:</strong> She <em>has been reading</em> for 2 hours.</div><h2>Past Tense (4 Types)</h2><table><tr><th>Tense</th><th>Structure</th><th>Example</th></tr><tr><td>Simple Past</td><td>Subject + V2</td><td>She <em>read</em> a book.</td></tr><tr><td>Past Continuous</td><td>Subject + was/were + V-ing</td><td>She <em>was reading</em>.</td></tr><tr><td>Past Perfect</td><td>Subject + had + V3</td><td>She <em>had read</em> it.</td></tr><tr><td>Past Perfect Continuous</td><td>Subject + had been + V-ing</td><td>She <em>had been reading</em>.</td></tr></table><h2>Future Tense (4 Types)</h2><table><tr><th>Tense</th><th>Structure</th><th>Example</th></tr><tr><td>Simple Future</td><td>Subject + will + V1</td><td>She <em>will read</em> it.</td></tr><tr><td>Future Continuous</td><td>Subject + will be + V-ing</td><td>She <em>will be reading</em>.</td></tr><tr><td>Future Perfect</td><td>Subject + will have + V3</td><td>She <em>will have read</em> it.</td></tr><tr><td>Future Perfect Continuous</td><td>Subject + will have been + V-ing</td><td>She <em>will have been reading</em>.</td></tr></table><div class='highlight-box'><strong>Memory Trick:</strong> V1 = Base form (go), V2 = Past form (went), V3 = Past Participle (gone)</div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to English Grammar: All 12 Tenses Explained with Examples.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>काल (Tenses) का परिचय</h2><p>काल से हमें पता चलता है कि कोई कार्य कब हुआ - वर्तमान, भूत या भविष्य में।</p><h2>वर्तमान काल के 4 प्रकार</h2><table><tr><th>काल</th><th>संरचना</th><th>उदाहरण</th></tr><tr><td>सामान्य वर्तमान</td><td>Subject + V1</td><td>वह पढ़ती है।</td></tr><tr><td>अपूर्ण वर्तमान</td><td>Subject + is/am/are + V-ing</td><td>वह पढ़ रही है।</td></tr></table>"
    },
    {
      "id": 4,
      "slug": "french-revolution",
      "title": "The French Revolution: Causes, Events and Impact",
      "title_hi": "फ्रांसीसी क्रांति: कारण, घटनाएं और प्रभाव",
      "category": "school",
      "emoji": "🏰",
      "excerpt": "Complete study guide on the French Revolution for Class 9 History. Learn about the causes, major events, important leaders and its global impact.",
      "author": "Dr. Amit Tripathi",
      "date": "2024-02-10",
      "readTime": 9,
      "featured": false,
      "tags": [
        "history",
        "class-9",
        "french-revolution",
        "world-history"
      ],
      "content": "<h2>Introduction</h2><p>The <strong>French Revolution (1789–1799)</strong> was one of the most significant political and social upheavals in world history. It overthrew the monarchy, established a republic, and had profound effects not just on France but on the entire world.</p><h2>Causes of the French Revolution</h2><h3>1. Social Inequality (The Three Estates)</h3><p>French society was divided into three estates:</p><ul><li><strong>First Estate:</strong> Clergy (less than 1% of population, owned 10% of land)</li><li><strong>Second Estate:</strong> Nobility (about 2%, paid no taxes)</li><li><strong>Third Estate:</strong> Common people (97% of population, paid all taxes)</li></ul><h3>2. Economic Crisis</h3><ul><li>France was bankrupt after wars (including helping American Revolution)</li><li>Poor harvests led to food shortages and starvation</li><li>Heavy taxation on the Third Estate</li></ul><h3>3. Political Causes</h3><ul><li>Weak leadership of <strong>King Louis XVI</strong></li><li>No representation for common people in government</li><li>Inspiration from American Revolution (1776)</li></ul><h3>4. Philosophical Influence</h3><p>The ideas of <strong>Enlightenment philosophers</strong> like Voltaire, Rousseau, and Montesquieu inspired people with concepts of liberty, equality, and fraternity.</p><h2>Major Events</h2><table><tr><th>Date</th><th>Event</th></tr><tr><td>1789, May</td><td>Estates-General convened</td></tr><tr><td>1789, June</td><td>Third Estate forms National Assembly</td></tr><tr><td>1789, July 14</td><td>Storming of the Bastille (Revolution begins)</td></tr><tr><td>1789, August</td><td>Declaration of Rights of Man and Citizen</td></tr><tr><td>1793</td><td>King Louis XVI executed</td></tr><tr><td>1793-94</td><td>Reign of Terror under Robespierre</td></tr><tr><td>1799</td><td>Napoleon Bonaparte takes power</td></tr></table><div class='highlight-box'><strong>Key Slogan:</strong> Liberté, Égalité, Fraternité (Liberty, Equality, Fraternity) — This became the motto of France and inspired revolutions worldwide.</div><h2>Impact of French Revolution</h2><ul><li>🌍 Spread ideas of democracy and human rights worldwide</li><li>⚖️ Abolished feudalism and privileges of nobility</li><li>📜 Inspired many future revolutions in Europe and Latin America</li><li>🗳️ Promoted concept of nationalism</li><li>⚔️ Led to rise of Napoleon Bonaparte</li></ul>",
      "content_hi": "<h2>फ्रांसीसी क्रांति (1789-1799)</h2><p>फ्रांसीसी क्रांति विश्व इतिहास की सबसे महत्वपूर्ण घटनाओं में से एक है जिसने राजतंत्र को उखाड़ फेंका।</p><h2>कारण</h2><ul><li>सामाजिक असमानता - तीन वर्गों में विभाजित समाज</li><li>आर्थिक संकट - भारी कर और अकाल</li><li>राजा लुई XVI का कमजोर शासन</li><li>ज्ञानोदय के दार्शनिकों का प्रभाव</li></ul><h2>मुख्य नारा</h2><div class='highlight-box'>स्वतंत्रता, समानता, बंधुत्व (Liberté, Égalité, Fraternité)</div>"
    },
    {
      "id": 5,
      "slug": "periodic-table-elements",
      "title": "Periodic Table: Elements, Groups and Properties Explained",
      "title_hi": "आवर्त सारणी: तत्व, समूह और गुण",
      "category": "school",
      "emoji": "⚗️",
      "excerpt": "Learn the Periodic Table systematically - groups, periods, properties of elements. Complete guide for Class 10 Chemistry with tricks to memorize.",
      "author": "Dr. Priya Sharma",
      "date": "2024-02-20",
      "readTime": 8,
      "featured": false,
      "tags": [
        "chemistry",
        "class-10",
        "periodic-table",
        "elements",
        "science"
      ],
      "content": "<h2>What is the Periodic Table?</h2><p>The Periodic Table is an organized arrangement of all known <strong>118 chemical elements</strong> based on their atomic number, electron configuration, and chemical properties. It was developed by <strong>Dmitri Mendeleev</strong> in 1869.</p><div class='highlight-box'><strong>Modern Periodic Law:</strong> Properties of elements are a periodic function of their atomic numbers.</div><h2>Structure of the Periodic Table</h2><h3>Periods (Horizontal Rows)</h3><p>There are <strong>7 periods</strong> in the Periodic Table. Each period represents a new electron shell.</p><table><tr><th>Period</th><th>Elements</th><th>Shells</th></tr><tr><td>Period 1</td><td>2 elements (H, He)</td><td>1 shell</td></tr><tr><td>Period 2</td><td>8 elements (Li to Ne)</td><td>2 shells</td></tr><tr><td>Period 3</td><td>8 elements (Na to Ar)</td><td>3 shells</td></tr><tr><td>Period 4</td><td>18 elements</td><td>4 shells</td></tr></table><h3>Groups (Vertical Columns)</h3><p>There are <strong>18 groups</strong>. Elements in the same group have similar chemical properties.</p><ul><li><strong>Group 1:</strong> Alkali Metals (Li, Na, K, Rb, Cs, Fr)</li><li><strong>Group 2:</strong> Alkaline Earth Metals (Be, Mg, Ca, Sr, Ba, Ra)</li><li><strong>Group 17:</strong> Halogens (F, Cl, Br, I, At)</li><li><strong>Group 18:</strong> Noble Gases (He, Ne, Ar, Kr, Xe, Rn)</li></ul><h2>Memory Tricks</h2><div class='fact-box'><strong>First 20 Elements Trick:</strong><br>H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca<br><br><em>\"HaHa LiBe BCN OF NeNa MgAlSi PS ClAr KCa\"</em></div><h2>Important Properties</h2><table><tr><th>Property</th><th>Across Period (→)</th><th>Down Group (↓)</th></tr><tr><td>Atomic Size</td><td>Decreases</td><td>Increases</td></tr><tr><td>Metallic Character</td><td>Decreases</td><td>Increases</td></tr><tr><td>Electronegativity</td><td>Increases</td><td>Decreases</td></tr><tr><td>Ionization Energy</td><td>Increases</td><td>Decreases</td></tr></table><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Periodic Table: Elements, Groups and Properties Explained.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>आवर्त सारणी</h2><p>आवर्त सारणी में 118 तत्वों को उनके परमाणु क्रमांक के आधार पर व्यवस्थित किया गया है। इसे <strong>दमित्री मेंडेलीव</strong> ने 1869 में बनाया था।</p><h2>याद करने की ट्रिक</h2><div class='fact-box'>पहले 20 तत्व: H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca</div>"
    },
    {
      "id": 6,
      "slug": "indian-freedom-struggle",
      "title": "Indian Freedom Struggle: Key Events, Leaders and Movements",
      "title_hi": "भारतीय स्वतंत्रता संग्राम: प्रमुख घटनाएं और आंदोलन",
      "category": "school",
      "emoji": "🇮🇳",
      "excerpt": "Complete guide to India's Independence Movement from 1857 to 1947. Learn about key events, leaders like Gandhi, Nehru, Bose and their contributions.",
      "author": "Prof. Meena Joshi",
      "date": "2024-03-01",
      "readTime": 11,
      "featured": false,
      "tags": [
        "history",
        "india",
        "freedom-struggle",
        "class-8",
        "gandhi"
      ],
      "content": "<h2>Introduction</h2><p>India's struggle for independence from British rule lasted nearly <strong>200 years</strong>, from the First War of Independence in 1857 to finally achieving freedom on <strong>August 15, 1947</strong>.</p><h2>Timeline of Major Events</h2><table><tr><th>Year</th><th>Event</th><th>Significance</th></tr><tr><td>1857</td><td>First War of Independence</td><td>First major uprising against British rule</td></tr><tr><td>1885</td><td>Indian National Congress founded</td><td>First major political organization</td></tr><tr><td>1905</td><td>Partition of Bengal</td><td>Sparked mass protest; Swadeshi Movement</td></tr><tr><td>1919</td><td>Jallianwala Bagh Massacre</td><td>Turned national sentiment against British</td></tr><tr><td>1920-22</td><td>Non-Cooperation Movement</td><td>Gandhi's first mass movement</td></tr><tr><td>1930</td><td>Civil Disobedience / Dandi March</td><td>Salt March by Gandhi</td></tr><tr><td>1942</td><td>Quit India Movement</td><td>'Do or Die' — final push for freedom</td></tr><tr><td>1947</td><td>Independence</td><td>India becomes free on August 15</td></tr></table><h2>Key Leaders</h2><div class='highlight-box'><strong>Mahatma Gandhi</strong> (Father of the Nation)<br>Known for: Non-violent resistance (Satyagraha), Civil Disobedience, Quit India Movement</div><div class='fact-box'><strong>Other Key Leaders:</strong><ul><li>🎯 <strong>Bal Gangadhar Tilak</strong> — \"Swaraj is my birthright\" — Father of Indian Unrest</li><li>🦁 <strong>Subhas Chandra Bose</strong> — Founded INA; \"Jai Hind\" — Netaji</li><li>🌹 <strong>Jawaharlal Nehru</strong> — First Prime Minister; Tryst with Destiny speech</li><li>⚖️ <strong>B.R. Ambedkar</strong> — Father of Indian Constitution</li><li>🔥 <strong>Bhagat Singh</strong> — Revolutionary freedom fighter</li></ul></div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Indian Freedom Struggle: Key Events, Leaders and Movements.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>भारतीय स्वतंत्रता संग्राम</h2><p>भारत ने 1857 से 1947 तक लगभग 200 साल की लड़ाई के बाद 15 अगस्त 1947 को स्वतंत्रता प्राप्त की।</p><h2>प्रमुख नेता</h2><ul><li><strong>महात्मा गांधी</strong> - राष्ट्रपिता, अहिंसा के पुजारी</li><li><strong>नेताजी सुभाष चंद्र बोस</strong> - आजाद हिंद फौज</li><li><strong>जवाहरलाल नेहरू</strong> - प्रथम प्रधानमंत्री</li><li><strong>भगत सिंह</strong> - क्रांतिकारी</li></ul>"
    },
    {
      "id": 7,
      "slug": "fractions-decimals-percentages",
      "title": "Fractions, Decimals and Percentages: Complete Math Guide",
      "title_hi": "भिन्न, दशमलव और प्रतिशत: सम्पूर्ण गणित गाइड",
      "category": "school",
      "emoji": "🔢",
      "excerpt": "Master fractions, decimals and percentages with easy tricks and formulas. Perfect for Class 6-8 students with solved examples and practice questions.",
      "author": "Mr. Vikas Gupta",
      "date": "2024-03-10",
      "readTime": 9,
      "featured": false,
      "tags": [
        "math",
        "fractions",
        "decimals",
        "class-6",
        "class-7",
        "class-8"
      ],
      "content": "<h2>What are Fractions?</h2><p>A fraction represents a <strong>part of a whole</strong>. It has two parts: <strong>Numerator</strong> (top number) and <strong>Denominator</strong> (bottom number).</p><div class='fact-box'><strong>Example:</strong> In the fraction 3/4 → Numerator = 3, Denominator = 4<br>This means 3 parts out of 4 equal parts.</div><h2>Types of Fractions</h2><table><tr><th>Type</th><th>Definition</th><th>Example</th></tr><tr><td>Proper Fraction</td><td>Numerator less than denominator</td><td>3/4, 2/5</td></tr><tr><td>Improper Fraction</td><td>Numerator greater than denominator</td><td>5/3, 7/4</td></tr><tr><td>Mixed Number</td><td>Whole number + proper fraction</td><td>2½, 3¾</td></tr><tr><td>Like Fractions</td><td>Same denominator</td><td>1/4, 3/4</td></tr><tr><td>Unlike Fractions</td><td>Different denominators</td><td>1/3, 1/4</td></tr></table><h2>Converting Between Fractions, Decimals and Percentages</h2><div class='highlight-box'><strong>Fraction → Decimal:</strong> Divide numerator by denominator<br>3/4 = 3 ÷ 4 = 0.75<br><br><strong>Decimal → Percentage:</strong> Multiply by 100<br>0.75 × 100 = 75%<br><br><strong>Percentage → Fraction:</strong> Divide by 100<br>75% = 75/100 = 3/4</div><h2>Important Percentage Formulas</h2><ul><li>Percentage of a number: (Percentage × Number) / 100</li><li>Percentage increase: [(New - Old) / Old] × 100</li><li>Percentage decrease: [(Old - New) / Old] × 100</li></ul><div class='fact-box'><strong>Common Fraction-Decimal-Percentage Table:</strong><table><tr><th>Fraction</th><th>Decimal</th><th>Percentage</th></tr><tr><td>1/2</td><td>0.5</td><td>50%</td></tr><tr><td>1/4</td><td>0.25</td><td>25%</td></tr><tr><td>3/4</td><td>0.75</td><td>75%</td></tr><tr><td>1/3</td><td>0.333</td><td>33.3%</td></tr><tr><td>1/5</td><td>0.2</td><td>20%</td></tr></table></div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Fractions, Decimals and Percentages: Complete Math Guide.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>भिन्न (Fractions)</h2><p>भिन्न किसी पूर्ण वस्तु के एक भाग को दर्शाता है। इसमें अंश (ऊपर) और हर (नीचे) होते हैं।</p><h2>रूपांतरण (Conversion)</h2><div class='highlight-box'>भिन्न → दशमलव: अंश को हर से भाग दें<br>प्रतिशत → भिन्न: 100 से भाग दें</div>"
    },
    {
      "id": 8,
      "slug": "fundamental-rights-india",
      "title": "Fundamental Rights in Indian Constitution: Complete Guide",
      "title_hi": "भारतीय संविधान में मौलिक अधिकार: सम्पूर्ण गाइड",
      "category": "competitive",
      "emoji": "⚖️",
      "excerpt": "Learn all 6 Fundamental Rights from Articles 12-35. Essential for UPSC, SSC, State PSC and all competitive exams with important case laws.",
      "author": "Adv. Ramesh Mishra",
      "date": "2024-01-25",
      "readTime": 10,
      "featured": true,
      "tags": [
        "constitution",
        "upsc",
        "ssc",
        "fundamental-rights",
        "polity"
      ],
      "content": "<h2>Introduction to Fundamental Rights</h2><p>Fundamental Rights are the basic rights guaranteed to all citizens of India by the <strong>Indian Constitution (Part III, Articles 12-35)</strong>. They protect individuals from arbitrary state action and are enforceable by the Supreme Court and High Courts.</p><div class='highlight-box'><strong>Key Feature:</strong> Fundamental Rights are justiciable — you can go to court if they are violated!</div><h2>The 6 Fundamental Rights</h2><h3>1. Right to Equality (Articles 14-18)</h3><table><tr><th>Article</th><th>Provision</th></tr><tr><td>Article 14</td><td>Equality before law</td></tr><tr><td>Article 15</td><td>No discrimination on basis of religion, race, caste, sex, birthplace</td></tr><tr><td>Article 16</td><td>Equal opportunity in public employment</td></tr><tr><td>Article 17</td><td>Abolition of Untouchability</td></tr><tr><td>Article 18</td><td>Abolition of Titles (except military/academic)</td></tr></table><h3>2. Right to Freedom (Articles 19-22)</h3><ul><li><strong>Article 19:</strong> 6 freedoms (speech, assembly, association, movement, residence, profession)</li><li><strong>Article 20:</strong> Protection against arbitrary arrest</li><li><strong>Article 21:</strong> Right to Life and Personal Liberty (most important!)</li><li><strong>Article 21A:</strong> Right to Education (6-14 years age group)</li><li><strong>Article 22:</strong> Protection against detention</li></ul><h3>3. Right Against Exploitation (Articles 23-24)</h3><ul><li><strong>Article 23:</strong> Prohibition of traffic in human beings and forced labour</li><li><strong>Article 24:</strong> Prohibition of employment of children below 14 years in factories</li></ul><h3>4. Right to Freedom of Religion (Articles 25-28)</h3><ul><li><strong>Article 25:</strong> Freedom of conscience and religion</li><li><strong>Article 26:</strong> Freedom to manage religious affairs</li><li><strong>Article 27:</strong> Freedom from paying taxes for promotion of religion</li><li><strong>Article 28:</strong> Freedom from religious instruction in state-funded schools</li></ul><h3>5. Cultural and Educational Rights (Articles 29-30)</h3><ul><li><strong>Article 29:</strong> Protection of interests of minorities</li><li><strong>Article 30:</strong> Right of minorities to establish educational institutions</li></ul><h3>6. Right to Constitutional Remedies (Article 32)</h3><div class='fact-box'><strong>\"Heart and Soul\" of the Constitution — Dr. B.R. Ambedkar</strong><br><br>Article 32 gives the right to move Supreme Court for enforcement of Fundamental Rights. The Supreme Court can issue 5 types of writs:<br><ul><li>Habeas Corpus — \"Have the body\"</li><li>Mandamus — \"We command\"</li><li>Prohibition — Stop inferior court</li><li>Certiorari — Transfer records</li><li>Quo Warranto — By what authority</li></ul></div><div class='highlight-box'><strong>Important:</strong> Originally there were 7 Fundamental Rights. The <strong>Right to Property (Article 31)</strong> was removed by the <strong>44th Constitutional Amendment, 1978</strong>. Now it is a legal right under Article 300A.</div>",
      "content_hi": "<h2>मौलिक अधिकार (Fundamental Rights)</h2><p>भारतीय संविधान के भाग III (अनुच्छेद 12-35) में 6 मौलिक अधिकार दिए गए हैं।</p><h2>6 मौलिक अधिकार</h2><ol><li>समानता का अधिकार (अनु. 14-18)</li><li>स्वतंत्रता का अधिकार (अनु. 19-22)</li><li>शोषण के विरुद्ध अधिकार (अनु. 23-24)</li><li>धर्म की स्वतंत्रता का अधिकार (अनु. 25-28)</li><li>सांस्कृतिक और शिक्षा संबंधी अधिकार (अनु. 29-30)</li><li>संवैधानिक उपचारों का अधिकार (अनु. 32)</li></ol>"
    },
    {
      "id": 9,
      "slug": "ssc-cgl-preparation-guide",
      "title": "SSC CGL 2024 Complete Preparation Guide: Strategy, Syllabus and Tips",
      "title_hi": "SSC CGL 2024 सम्पूर्ण तैयारी गाइड: रणनीति, पाठ्यक्रम और टिप्स",
      "category": "competitive",
      "emoji": "🏆",
      "excerpt": "Complete SSC CGL preparation guide including syllabus, exam pattern, subject-wise strategy and time management tips for cracking SSC CGL.",
      "author": "Saurabh Pandey",
      "date": "2024-02-05",
      "readTime": 12,
      "featured": false,
      "tags": [
        "ssc",
        "ssc-cgl",
        "competitive-exam",
        "preparation",
        "government-job"
      ],
      "content": "<h2>What is SSC CGL?</h2><p>SSC CGL (Staff Selection Commission - Combined Graduate Level) is one of India's most competitive exams for recruitment to various Group B and Group C posts in the Government of India departments.</p><div class='highlight-box'><strong>Posts Offered:</strong> Assistant Audit Officer, Income Tax Inspector, Sub-Inspector (CBI), Assistant Section Officer, Tax Assistant, and many more.</div><h2>SSC CGL 2024 Exam Pattern</h2><table><tr><th>Tier</th><th>Type</th><th>Subjects</th><th>Questions</th><th>Marks</th><th>Time</th></tr><tr><td>Tier 1</td><td>CBT (Online)</td><td>GI, English, Quantitative, GK</td><td>100</td><td>200</td><td>60 min</td></tr><tr><td>Tier 2</td><td>CBT (Online)</td><td>Math+Reasoning, English</td><td>Variable</td><td>Variable</td><td>2.5 hrs</td></tr></table><h2>Subject-wise Preparation Strategy</h2><h3>1. Quantitative Aptitude (Most Important)</h3><ul><li>📌 Topics: Number System, Percentage, Ratio, Time & Work, Algebra, Geometry, Trigonometry, Data Interpretation</li><li>📌 Daily Practice: 50+ questions/day</li><li>📌 Focus: Accuracy over speed initially, then speed</li><li>📌 Best Books: Rakesh Yadav, RS Aggarwal</li></ul><h3>2. English Language</h3><ul><li>📌 Topics: Reading Comprehension, Cloze Test, Error Spotting, Sentence Improvement, Para Jumbles</li><li>📌 Daily Practice: Read newspaper (The Hindu or Indian Express)</li><li>📌 Vocab: Learn 10 new words daily</li></ul><h3>3. General Intelligence & Reasoning</h3><ul><li>📌 Topics: Analogies, Series, Matrix, Coding-Decoding, Blood Relations, Direction Test</li><li>📌 This section is scoring — target 100% accuracy</li></ul><h3>4. General Awareness</h3><ul><li>📌 Static GK: History, Geography, Polity, Economy, Science</li><li>📌 Current Affairs: Last 6 months</li><li>📌 Read: Lucent's GK + Monthly current affairs magazine</li></ul><h2>Monthly Study Plan</h2><div class='fact-box'><strong>Month 1-2:</strong> Complete syllabus study<br><strong>Month 3-4:</strong> Revision + Mock tests (50+ tests)<br><strong>Month 5:</strong> Weak area focus + Previous year papers<br><strong>Last Month:</strong> Daily mock tests + revision</div><h2>Daily Schedule (8 Hours)</h2><ul><li>⏰ 6-8 AM: Quantitative Aptitude (2 hrs)</li><li>⏰ 9-11 AM: English (2 hrs)</li><li>⏰ 12-1 PM: General Knowledge (1 hr)</li><li>⏰ 3-5 PM: Reasoning (2 hrs)</li><li>⏰ 8-9 PM: Current Affairs + Revision (1 hr)</li></ul><div class='highlight-box'><strong>Top Tip:</strong> Solve at least 10 previous year papers. SSC often repeats questions with minor variations!</div>",
      "content_hi": "<h2>SSC CGL क्या है?</h2><p>SSC CGL भारत सरकार के विभिन्न विभागों में Group B और C पदों पर भर्ती के लिए एक प्रतिष्ठित परीक्षा है।</p><h2>परीक्षा पैटर्न</h2><table><tr><th>चरण</th><th>विषय</th><th>प्रश्न</th><th>अंक</th></tr><tr><td>Tier 1</td><td>GI, English, गणित, GK</td><td>100</td><td>200</td></tr></table>"
    },
    {
      "id": 10,
      "slug": "important-abbreviations-competitive-exams",
      "title": "500+ Important Abbreviations for Competitive Exams (A-Z)",
      "title_hi": "प्रतियोगी परीक्षाओं के लिए 500+ महत्वपूर्ण संक्षिप्त रूप",
      "category": "competitive",
      "emoji": "📝",
      "excerpt": "Complete list of important abbreviations and full forms for SSC, UPSC, Banking, Railway exams. Learn A-Z abbreviations with categories.",
      "author": "Ms. Sunita Verma",
      "date": "2024-02-15",
      "readTime": 8,
      "featured": false,
      "tags": [
        "abbreviations",
        "full-forms",
        "ssc",
        "upsc",
        "banking",
        "general-knowledge"
      ],
      "content": "<h2>Why Abbreviations Matter?</h2><p>Abbreviations and full forms are asked in almost every competitive exam — SSC, UPSC, Banking, Railway, Police etc. This comprehensive list covers all important ones.</p><h2>Banking & Finance</h2><table><tr><th>Abbreviation</th><th>Full Form</th></tr><tr><td>RBI</td><td>Reserve Bank of India</td></tr><tr><td>NABARD</td><td>National Bank for Agriculture and Rural Development</td></tr><tr><td>SEBI</td><td>Securities and Exchange Board of India</td></tr><tr><td>GDP</td><td>Gross Domestic Product</td></tr><tr><td>GNP</td><td>Gross National Product</td></tr><tr><td>IMF</td><td>International Monetary Fund</td></tr><tr><td>WTO</td><td>World Trade Organization</td></tr><tr><td>ATM</td><td>Automated Teller Machine</td></tr><tr><td>NEFT</td><td>National Electronic Funds Transfer</td></tr><tr><td>RTGS</td><td>Real Time Gross Settlement</td></tr></table><h2>Science & Technology</h2><table><tr><th>Abbreviation</th><th>Full Form</th></tr><tr><td>ISRO</td><td>Indian Space Research Organisation</td></tr><tr><td>NASA</td><td>National Aeronautics and Space Administration</td></tr><tr><td>DNA</td><td>Deoxyribonucleic Acid</td></tr><tr><td>RNA</td><td>Ribonucleic Acid</td></tr><tr><td>CPU</td><td>Central Processing Unit</td></tr><tr><td>RAM</td><td>Random Access Memory</td></tr><tr><td>GPS</td><td>Global Positioning System</td></tr><tr><td>WWW</td><td>World Wide Web</td></tr><tr><td>AI</td><td>Artificial Intelligence</td></tr><tr><td>LASER</td><td>Light Amplification by Stimulated Emission of Radiation</td></tr></table><h2>Government & Politics</h2><table><tr><th>Abbreviation</th><th>Full Form</th></tr><tr><td>UNO</td><td>United Nations Organization</td></tr><tr><td>WHO</td><td>World Health Organization</td></tr><tr><td>UNESCO</td><td>United Nations Educational, Scientific and Cultural Organization</td></tr><tr><td>UNICEF</td><td>United Nations International Children's Emergency Fund</td></tr><tr><td>IPC</td><td>Indian Penal Code</td></tr><tr><td>CBI</td><td>Central Bureau of Investigation</td></tr><tr><td>RAW</td><td>Research and Analysis Wing</td></tr><tr><td>NDA</td><td>National Defence Academy</td></tr><tr><td>UPSC</td><td>Union Public Service Commission</td></tr><tr><td>SSC</td><td>Staff Selection Commission</td></tr></table><h2>Sports</h2><table><tr><th>Abbreviation</th><th>Full Form</th></tr><tr><td>ICC</td><td>International Cricket Council</td></tr><tr><td>FIFA</td><td>Fédération Internationale de Football Association</td></tr><tr><td>IOC</td><td>International Olympic Committee</td></tr><tr><td>BCCI</td><td>Board of Control for Cricket in India</td></tr><tr><td>IPL</td><td>Indian Premier League</td></tr></table><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to 500+ Important Abbreviations for Competitive Exams (A-Z).</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>महत्वपूर्ण संक्षिप्त रूप</h2><p>प्रतियोगी परीक्षाओं में संक्षिप्त रूप (Abbreviations) से संबंधित प्रश्न अवश्य पूछे जाते हैं।</p><table><tr><th>संक्षिप्त रूप</th><th>पूरा नाम</th></tr><tr><td>RBI</td><td>भारतीय रिज़र्व बैंक</td></tr><tr><td>ISRO</td><td>भारतीय अंतरिक्ष अनुसंधान संगठन</td></tr><tr><td>UPSC</td><td>संघ लोक सेवा आयोग</td></tr></table>"
    },
    {
      "id": 11,
      "slug": "reasoning-tricks-competitive-exams",
      "title": "Reasoning Tricks and Shortcuts for All Competitive Exams",
      "title_hi": "प्रतियोगी परीक्षाओं के लिए रीजनिंग ट्रिक्स और शॉर्टकट",
      "category": "competitive",
      "emoji": "🧠",
      "excerpt": "Master logical reasoning with proven tricks and shortcuts. Learn Analogy, Series, Coding-Decoding, Blood Relations, Direction Test and more.",
      "author": "Saurabh Pandey",
      "date": "2024-03-05",
      "readTime": 10,
      "featured": false,
      "tags": [
        "reasoning",
        "logical",
        "ssc",
        "banking",
        "shortcuts",
        "tricks"
      ],
      "content": "<h2>Why Reasoning is Important?</h2><p>Reasoning section is asked in almost all competitive exams — SSC, Banking, Railway, Police, UPSC. It tests your <strong>logical thinking and problem-solving</strong> ability. With proper tricks, you can solve questions in 10-15 seconds!</p><h2>1. Number Series</h2><p>Find the missing number by identifying the pattern.</p><div class='fact-box'><strong>Common Patterns:</strong><ul><li>+2, +4, +6, +8... (increasing difference)</li><li>×2, ×3, ×4... (multiplication series)</li><li>Prime numbers: 2, 3, 5, 7, 11, 13...</li><li>Perfect squares: 1, 4, 9, 16, 25, 36...</li><li>Fibonacci: 1, 1, 2, 3, 5, 8, 13...</li></ul></div><h2>2. Coding-Decoding</h2><div class='highlight-box'><strong>Trick:</strong> If A=1, B=2... Z=26, then:<br>FACE → 6+1+3+5 = 15<br><br>Position Reverse: Z=1, Y=2... A=26<br>Opposite Letter: A↔Z, B↔Y, C↔X (add up to 27)</div><h2>3. Blood Relations</h2><p>Draw a family tree to solve easily:</p><ul><li>Son's son = Grandson</li><li>Brother's daughter = Niece</li><li>Mother's brother = Maternal Uncle (Mama)</li><li>Father's sister = Paternal Aunt (Bua/Phuphi)</li><li>Mother's sister = Maternal Aunt (Mausi)</li></ul><h2>4. Direction Test</h2><div class='fact-box'><strong>Important Rule:</strong><br>After rotating Right (clockwise): North→East→South→West<br>After rotating Left (anti-clockwise): North→West→South→East<br><br>Shadow Direction: Morning shadow = West, Evening shadow = East, Noon shadow = North</div><h2>5. Analogy</h2><p>Find the relationship between the first pair and apply it to the second pair.</p><table><tr><th>Example</th><th>Relationship</th></tr><tr><td>Doctor : Hospital :: Teacher : ?</td><td>Place of work → School</td></tr><tr><td>Book : Library :: Painting : ?</td><td>Place of storage → Museum/Gallery</td></tr><tr><td>Fish : Water :: Bird : ?</td><td>Natural habitat → Air/Sky</td></tr></table><div class='highlight-box'><strong>Golden Rule:</strong> In Reasoning, always attempt questions you are 100% sure of first. Don't waste time on tricky questions in the exam.</div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Reasoning Tricks and Shortcuts for All Competitive Exams.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>रीजनिंग में सफलता के टिप्स</h2><p>रीजनिंग में सही तकनीक से कठिन प्रश्न भी आसान हो जाते हैं।</p><h2>संख्या श्रेणी के नियम</h2><div class='fact-box'>+2, +4, +6 (बढ़ता अंतर) | ×2, ×3 (गुणन) | अभाज्य संख्याएं | वर्ग संख्याएं</div>"
    },
    {
      "id": 12,
      "slug": "computer-knowledge-basics",
      "title": "Basic Computer Knowledge for Competitive Exams: Complete Guide",
      "title_hi": "प्रतियोगी परीक्षाओं के लिए कंप्यूटर ज्ञान",
      "category": "competitive",
      "emoji": "💻",
      "excerpt": "Complete computer knowledge guide for SSC, Banking, Railway exams. Learn hardware, software, internet, MS Office shortcuts and more.",
      "author": "Mr. Vikas Gupta",
      "date": "2024-03-15",
      "readTime": 9,
      "featured": false,
      "tags": [
        "computer",
        "ssc",
        "banking",
        "ccc",
        "ms-office",
        "internet"
      ],
      "content": "<h2>Introduction to Computers</h2><p>A computer is an <strong>electronic device</strong> that accepts data (input), processes it, and gives output. It works based on the <strong>IPO cycle</strong>: Input → Process → Output.</p><h2>Generations of Computers</h2><table><tr><th>Generation</th><th>Period</th><th>Technology</th><th>Example</th></tr><tr><td>1st</td><td>1940-1956</td><td>Vacuum Tubes</td><td>ENIAC, UNIVAC</td></tr><tr><td>2nd</td><td>1956-1963</td><td>Transistors</td><td>IBM 1401</td></tr><tr><td>3rd</td><td>1964-1971</td><td>Integrated Circuits (IC)</td><td>IBM 360</td></tr><tr><td>4th</td><td>1971-present</td><td>Microprocessors</td><td>Personal Computers</td></tr><tr><td>5th</td><td>Present-future</td><td>AI, Parallel Processing</td><td>Modern AI Systems</td></tr></table><h2>Computer Hardware</h2><ul><li><strong>CPU (Central Processing Unit):</strong> Brain of the computer</li><li><strong>RAM (Random Access Memory):</strong> Temporary memory — lost when power off</li><li><strong>ROM (Read Only Memory):</strong> Permanent memory — stores BIOS</li><li><strong>Hard Disk:</strong> Permanent storage device</li><li><strong>Motherboard:</strong> Main circuit board connecting all components</li></ul><h2>Important Computer Terms</h2><table><tr><th>Term</th><th>Full Form / Meaning</th></tr><tr><td>URL</td><td>Uniform Resource Locator</td></tr><tr><td>HTML</td><td>HyperText Markup Language</td></tr><tr><td>HTTP</td><td>HyperText Transfer Protocol</td></tr><tr><td>HTTPS</td><td>HTTP Secure</td></tr><tr><td>IP</td><td>Internet Protocol</td></tr><tr><td>Wi-Fi</td><td>Wireless Fidelity</td></tr><tr><td>PDF</td><td>Portable Document Format</td></tr><tr><td>USB</td><td>Universal Serial Bus</td></tr><tr><td>SSD</td><td>Solid State Drive</td></tr><tr><td>OS</td><td>Operating System</td></tr></table><h2>MS Office Shortcuts</h2><div class='fact-box'><strong>Word/Excel/PowerPoint:</strong><ul><li>Ctrl+C = Copy | Ctrl+V = Paste | Ctrl+X = Cut</li><li>Ctrl+Z = Undo | Ctrl+Y = Redo</li><li>Ctrl+S = Save | Ctrl+P = Print</li><li>Ctrl+A = Select All | Ctrl+F = Find</li><li>Ctrl+B = Bold | Ctrl+I = Italic | Ctrl+U = Underline</li></ul></div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Basic Computer Knowledge for Competitive Exams.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>कंप्यूटर का परिचय</h2><p>कंप्यूटर एक इलेक्ट्रॉनिक उपकरण है जो IPO चक्र पर काम करता है: इनपुट → प्रोसेस → आउटपुट।</p><h2>महत्वपूर्ण शॉर्टकट</h2><div class='fact-box'>Ctrl+C = कॉपी | Ctrl+V = पेस्ट | Ctrl+S = सेव | Ctrl+Z = अनडू</div>"
    },
    {
      "id": 13,
      "slug": "seven-wonders-of-the-world",
      "title": "Seven Wonders of the World: Complete Information with Facts",
      "title_hi": "विश्व के सात अजूबे: सम्पूर्ण जानकारी और रोचक तथ्य",
      "category": "gk",
      "emoji": "🌍",
      "excerpt": "Learn about the New 7 Wonders of the World and the Ancient 7 Wonders with interesting facts, locations and history. Important for all competitive exams.",
      "author": "Prof. Meena Joshi",
      "date": "2024-01-30",
      "readTime": 7,
      "featured": true,
      "tags": [
        "gk",
        "world-wonders",
        "geography",
        "history",
        "current-affairs"
      ],
      "content": "<h2>New Seven Wonders of the World (2007)</h2><p>In 2007, over <strong>100 million people</strong> voted worldwide to select the new Seven Wonders of the World. The results were announced on July 7, 2007 (07/07/07).</p><table><tr><th>Wonder</th><th>Location</th><th>Built</th><th>Fact</th></tr><tr><td>🏯 Great Wall of China</td><td>China</td><td>7th century BC - 16th century AD</td><td>Over 21,000 km long</td></tr><tr><td>🏛️ Petra</td><td>Jordan</td><td>300 BC</td><td>Rose-red city carved in rock</td></tr><tr><td>🗿 Christ the Redeemer</td><td>Brazil (Rio de Janeiro)</td><td>1931</td><td>98 ft tall + 26 ft base</td></tr><tr><td>🏟️ Machu Picchu</td><td>Peru</td><td>15th century</td><td>Inca citadel at 7,970 ft altitude</td></tr><tr><td>🐍 Chichen Itza</td><td>Mexico</td><td>600 AD</td><td>Mayan pyramid</td></tr><tr><td>🏛️ Roman Colosseum</td><td>Italy (Rome)</td><td>70-80 AD</td><td>Held 50,000-80,000 spectators</td></tr><tr><td>🕌 Taj Mahal</td><td>India (Agra)</td><td>1643 AD</td><td>Built by Shah Jahan for Mumtaz</td></tr></table><div class='highlight-box'><strong>India's Pride:</strong> Taj Mahal — Built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It took 22 years and 20,000 workers to build!</div><h2>Ancient Seven Wonders (for Reference)</h2><table><tr><th>Wonder</th><th>Location</th><th>Status</th></tr><tr><td>Great Pyramid of Giza</td><td>Egypt</td><td>Still exists (only surviving ancient wonder)</td></tr><tr><td>Hanging Gardens of Babylon</td><td>Iraq</td><td>Destroyed</td></tr><tr><td>Statue of Zeus at Olympia</td><td>Greece</td><td>Destroyed</td></tr><tr><td>Temple of Artemis at Ephesus</td><td>Turkey</td><td>Destroyed</td></tr><tr><td>Mausoleum at Halicarnassus</td><td>Turkey</td><td>Destroyed</td></tr><tr><td>Colossus of Rhodes</td><td>Greece</td><td>Destroyed</td></tr><tr><td>Lighthouse of Alexandria</td><td>Egypt</td><td>Destroyed</td></tr></table><div class='fact-box'><strong>Interesting Facts:</strong><ul><li>Great Wall of China is NOT visible from space with naked eye (contrary to popular belief)</li><li>Taj Mahal changes color in different lighting — pinkish at dawn, milky white at noon, golden at night</li><li>Machu Picchu was never found by Spanish conquistadors</li><li>The Colosseum could be filled with water for mock naval battles</li></ul></div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Seven Wonders of the World: Complete Information with Facts.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>विश्व के सात नए अजूबे (2007)</h2><table><tr><th>अजूबा</th><th>देश</th></tr><tr><td>चीन की महान दीवार</td><td>चीन</td></tr><tr><td>पेत्रा</td><td>जॉर्डन</td></tr><tr><td>क्राइस्ट द रिडीमर</td><td>ब्राजील</td></tr><tr><td>माचू पिच्चू</td><td>पेरू</td></tr><tr><td>चिचेन इत्जा</td><td>मेक्सिको</td></tr><tr><td>रोमन कोलोसियम</td><td>इटली</td></tr><tr><td>ताज महल</td><td>भारत</td></tr></table><div class='highlight-box'>ताज महल को शाहजहाँ ने अपनी पत्नी मुमताज की याद में बनवाया था। इसे बनने में 22 साल लगे।</div>"
    },
    {
      "id": 14,
      "slug": "indian-states-and-capitals",
      "title": "Indian States and Union Territories: Capitals and Key Facts 2024",
      "title_hi": "भारत के राज्य और केंद्र शासित प्रदेश: राजधानियां 2024",
      "category": "gk",
      "emoji": "🗺️",
      "excerpt": "Complete list of all 28 States and 8 Union Territories of India with their capitals, formation dates, and important facts for all exams.",
      "author": "Dr. Amit Tripathi",
      "date": "2024-02-28",
      "readTime": 8,
      "featured": false,
      "tags": [
        "india",
        "states",
        "capitals",
        "geography",
        "gk",
        "upsc"
      ],
      "content": "<h2>India: Quick Facts</h2><div class='highlight-box'><strong>Total States:</strong> 28 | <strong>Union Territories:</strong> 8<br><strong>Capital:</strong> New Delhi | <strong>Largest State:</strong> Rajasthan | <strong>Smallest State:</strong> Goa</div><h2>All 28 States and Their Capitals</h2><table><tr><th>State</th><th>Capital</th><th>Formation Date</th></tr><tr><td>Andhra Pradesh</td><td>Amaravati</td><td>Nov 1, 1956</td></tr><tr><td>Arunachal Pradesh</td><td>Itanagar</td><td>Feb 20, 1987</td></tr><tr><td>Assam</td><td>Dispur</td><td>Jan 26, 1950</td></tr><tr><td>Bihar</td><td>Patna</td><td>Jan 26, 1950</td></tr><tr><td>Chhattisgarh</td><td>Raipur</td><td>Nov 1, 2000</td></tr><tr><td>Goa</td><td>Panaji</td><td>May 30, 1987</td></tr><tr><td>Gujarat</td><td>Gandhinagar</td><td>May 1, 1960</td></tr><tr><td>Haryana</td><td>Chandigarh</td><td>Nov 1, 1966</td></tr><tr><td>Himachal Pradesh</td><td>Shimla</td><td>Jan 25, 1971</td></tr><tr><td>Jharkhand</td><td>Ranchi</td><td>Nov 15, 2000</td></tr><tr><td>Karnataka</td><td>Bengaluru</td><td>Nov 1, 1956</td></tr><tr><td>Kerala</td><td>Thiruvananthapuram</td><td>Nov 1, 1956</td></tr><tr><td>Madhya Pradesh</td><td>Bhopal</td><td>Nov 1, 1956</td></tr><tr><td>Maharashtra</td><td>Mumbai</td><td>May 1, 1960</td></tr><tr><td>Manipur</td><td>Imphal</td><td>Jan 21, 1972</td></tr><tr><td>Meghalaya</td><td>Shillong</td><td>Jan 21, 1972</td></tr><tr><td>Mizoram</td><td>Aizawl</td><td>Feb 20, 1987</td></tr><tr><td>Nagaland</td><td>Kohima</td><td>Dec 1, 1963</td></tr><tr><td>Odisha</td><td>Bhubaneswar</td><td>Jan 26, 1950</td></tr><tr><td>Punjab</td><td>Chandigarh</td><td>Nov 1, 1966</td></tr><tr><td>Rajasthan</td><td>Jaipur</td><td>Mar 30, 1949</td></tr><tr><td>Sikkim</td><td>Gangtok</td><td>May 16, 1975</td></tr><tr><td>Tamil Nadu</td><td>Chennai</td><td>Jan 26, 1950</td></tr><tr><td>Telangana</td><td>Hyderabad</td><td>Jun 2, 2014</td></tr><tr><td>Tripura</td><td>Agartala</td><td>Jan 21, 1972</td></tr><tr><td>Uttar Pradesh</td><td>Lucknow</td><td>Jan 26, 1950</td></tr><tr><td>Uttarakhand</td><td>Dehradun</td><td>Nov 9, 2000</td></tr><tr><td>West Bengal</td><td>Kolkata</td><td>Jan 26, 1950</td></tr></table><h2>All 8 Union Territories and Their Capitals</h2><table><tr><th>Union Territory</th><th>Capital/HQ</th></tr><tr><td>Andaman & Nicobar Islands</td><td>Port Blair</td></tr><tr><td>Chandigarh</td><td>Chandigarh</td></tr><tr><td>Dadra & Nagar Haveli and Daman & Diu</td><td>Daman</td></tr><tr><td>Delhi (NCT)</td><td>New Delhi</td></tr><tr><td>Jammu & Kashmir</td><td>Srinagar (Summer), Jammu (Winter)</td></tr><tr><td>Ladakh</td><td>Leh</td></tr><tr><td>Lakshadweep</td><td>Kavaratti</td></tr><tr><td>Puducherry</td><td>Puducherry</td></tr></table><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Indian States and Union Territories: Capitals and Key Facts 2024.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>भारत के राज्य और राजधानियां</h2><p>भारत में कुल <strong>28 राज्य</strong> और <strong>8 केंद्र शासित प्रदेश</strong> हैं।</p><div class='highlight-box'>सबसे बड़ा राज्य: राजस्थान | सबसे छोटा राज्य: गोवा | राजधानी: नई दिल्ली</div>"
    },
    {
      "id": 15,
      "slug": "famous-scientists-inventions",
      "title": "Famous Scientists and Their Inventions: Complete GK Guide",
      "title_hi": "प्रसिद्ध वैज्ञानिक और उनके आविष्कार",
      "category": "gk",
      "emoji": "🔬",
      "excerpt": "Learn about world's greatest scientists and their groundbreaking inventions and discoveries. Essential GK for all competitive exams.",
      "author": "Dr. Priya Sharma",
      "date": "2024-03-08",
      "readTime": 7,
      "featured": false,
      "tags": [
        "scientists",
        "inventions",
        "discoveries",
        "gk",
        "science"
      ],
      "content": "<h2>Greatest Scientists in History</h2><table><tr><th>Scientist</th><th>Country</th><th>Major Contribution</th></tr><tr><td>Isaac Newton</td><td>England</td><td>Laws of Motion, Gravity, Calculus</td></tr><tr><td>Albert Einstein</td><td>Germany/USA</td><td>Theory of Relativity (E=mc²)</td></tr><tr><td>Charles Darwin</td><td>England</td><td>Theory of Evolution</td></tr><tr><td>Galileo Galilei</td><td>Italy</td><td>Telescope, Heliocentrism</td></tr><tr><td>Marie Curie</td><td>Poland/France</td><td>Radioactivity, Polonium, Radium</td></tr><tr><td>Thomas Edison</td><td>USA</td><td>Electric Bulb, Phonograph</td></tr><tr><td>Alexander Graham Bell</td><td>Scotland/USA</td><td>Telephone (1876)</td></tr><tr><td>Louis Pasteur</td><td>France</td><td>Germ Theory, Pasteurization, Vaccines</td></tr><tr><td>James Watt</td><td>Scotland</td><td>Steam Engine (improved)</td></tr><tr><td>Wright Brothers</td><td>USA</td><td>Airplane (1903)</td></tr></table><h2>Indian Scientists</h2><table><tr><th>Scientist</th><th>Achievement</th></tr><tr><td>C.V. Raman</td><td>Raman Effect — Nobel Prize Physics 1930</td></tr><tr><td>A.P.J. Abdul Kalam</td><td>Missile Man of India, PSLV, Agni missiles</td></tr><tr><td>Srinivasa Ramanujan</td><td>Mathematical formulas, Number theory</td></tr><tr><td>Jagadish Chandra Bose</td><td>Radio waves, Plant response</td></tr><tr><td>Homi Bhabha</td><td>Father of Indian Nuclear Programme</td></tr><tr><td>Vikram Sarabhai</td><td>Father of Indian Space Programme</td></tr></table><div class='highlight-box'><strong>Nobel Prize Winners (Science) — Key Points:</strong><ul><li>First woman Nobel Prize: Marie Curie (Physics 1903, Chemistry 1911)</li><li>First Indian Nobel (Science): C.V. Raman (Physics 1930)</li><li>Youngest Nobel (Physics): William Lawrence Bragg (25 years, 1915)</li></ul></div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Famous Scientists and Their Inventions: Complete GK Guide.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>प्रसिद्ध वैज्ञानिक</h2><table><tr><th>वैज्ञानिक</th><th>योगदान</th></tr><tr><td>न्यूटन</td><td>गुरुत्वाकर्षण, गति के नियम</td></tr><tr><td>आइंस्टीन</td><td>सापेक्षता का सिद्धांत (E=mc²)</td></tr><tr><td>सी.वी. रमन</td><td>रमन प्रभाव - नोबेल पुरस्कार 1930</td></tr><tr><td>A.P.J. अब्दुल कलाम</td><td>भारत के मिसाइल मैन</td></tr></table>"
    },
    {
      "id": 16,
      "slug": "important-days-dates-2024",
      "title": "Important National and International Days 2024: Complete List",
      "title_hi": "2024 के महत्वपूर्ण राष्ट्रीय और अंतर्राष्ट्रीय दिवस",
      "category": "gk",
      "emoji": "📅",
      "excerpt": "Complete list of important national and international days observed throughout the year. Essential for competitive exams, current affairs and GK.",
      "author": "Ms. Sunita Verma",
      "date": "2024-01-05",
      "readTime": 8,
      "featured": false,
      "tags": [
        "important-days",
        "current-affairs",
        "gk",
        "national-days",
        "international"
      ],
      "content": "<h2>January - March</h2><table><tr><th>Date</th><th>Day</th><th>Theme 2024</th></tr><tr><td>Jan 12</td><td>National Youth Day</td><td>Birthday of Swami Vivekananda</td></tr><tr><td>Jan 15</td><td>Indian Army Day</td><td>—</td></tr><tr><td>Jan 26</td><td>Republic Day (India)</td><td>India became Republic in 1950</td></tr><tr><td>Feb 4</td><td>World Cancer Day</td><td>Close the Care Gap</td></tr><tr><td>Feb 14</td><td>Valentine's Day</td><td>—</td></tr><tr><td>Feb 21</td><td>International Mother Language Day</td><td>UNESCO</td></tr><tr><td>Feb 28</td><td>National Science Day</td><td>Raman Effect discovered 1928</td></tr><tr><td>Mar 8</td><td>International Women's Day</td><td>Inspire Inclusion</td></tr><tr><td>Mar 21</td><td>World Down Syndrome Day</td><td>—</td></tr><tr><td>Mar 22</td><td>World Water Day</td><td>Water for Peace</td></tr></table><h2>April - June</h2><table><tr><th>Date</th><th>Day</th></tr><tr><td>Apr 5</td><td>National Maritime Day</td></tr><tr><td>Apr 7</td><td>World Health Day (WHO)</td></tr><tr><td>Apr 22</td><td>Earth Day</td></tr><tr><td>Apr 23</td><td>World Book Day</td></tr><tr><td>May 1</td><td>International Labour Day / May Day</td></tr><tr><td>May 3</td><td>World Press Freedom Day</td></tr><tr><td>May 11</td><td>National Technology Day (India)</td></tr><tr><td>Jun 5</td><td>World Environment Day</td></tr><tr><td>Jun 21</td><td>International Yoga Day</td></tr><tr><td>Jun 26</td><td>International Day Against Drug Abuse</td></tr></table><h2>July - December</h2><table><tr><th>Date</th><th>Day</th></tr><tr><td>Jul 11</td><td>World Population Day</td></tr><tr><td>Aug 6</td><td>Hiroshima Day</td></tr><tr><td>Aug 9</td><td>Quit India Day / Nagasaki Day</td></tr><tr><td>Aug 15</td><td>Independence Day (India)</td></tr><tr><td>Sep 5</td><td>Teachers' Day (India) — Dr. Radhakrishnan's Birthday</td></tr><tr><td>Oct 2</td><td>Gandhi Jayanti / International Non-Violence Day</td></tr><tr><td>Oct 16</td><td>World Food Day</td></tr><tr><td>Nov 14</td><td>Children's Day (India) — Nehru's Birthday</td></tr><tr><td>Dec 1</td><td>World AIDS Day</td></tr><tr><td>Dec 10</td><td>Human Rights Day</td></tr><tr><td>Dec 25</td><td>Christmas Day</td></tr></table><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Important National and International Days 2024: Complete List.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>महत्वपूर्ण दिन</h2><table><tr><th>तारीख</th><th>दिवस</th></tr><tr><td>26 जनवरी</td><td>गणतंत्र दिवस</td></tr><tr><td>15 अगस्त</td><td>स्वतंत्रता दिवस</td></tr><tr><td>5 सितंबर</td><td>शिक्षक दिवस</td></tr><tr><td>2 अक्टूबर</td><td>गांधी जयंती</td></tr><tr><td>14 नवंबर</td><td>बाल दिवस</td></tr></table>"
    },
    {
      "id": 17,
      "slug": "world-geography-major-rivers",
      "title": "World Geography: Major Rivers, Longest Mountains and Oceans",
      "title_hi": "विश्व भूगोल: प्रमुख नदियां, पर्वत और महासागर",
      "category": "gk",
      "emoji": "🏔️",
      "excerpt": "Complete world geography guide covering major rivers, highest mountains, largest oceans, continents and important geographical facts for exams.",
      "author": "Dr. Amit Tripathi",
      "date": "2024-03-20",
      "readTime": 9,
      "featured": false,
      "tags": [
        "geography",
        "rivers",
        "mountains",
        "world",
        "gk",
        "upsc"
      ],
      "content": "<h2>World's Longest Rivers</h2><table><tr><th>Rank</th><th>River</th><th>Continent</th><th>Length (km)</th></tr><tr><td>1</td><td>Nile</td><td>Africa</td><td>6,650</td></tr><tr><td>2</td><td>Amazon</td><td>South America</td><td>6,400</td></tr><tr><td>3</td><td>Yangtze</td><td>Asia (China)</td><td>6,300</td></tr><tr><td>4</td><td>Mississippi-Missouri</td><td>North America</td><td>6,275</td></tr><tr><td>5</td><td>Yenisei</td><td>Asia (Russia)</td><td>5,539</td></tr><tr><td>6</td><td>Ob-Irtysh</td><td>Asia (Russia)</td><td>5,410</td></tr><tr><td>7</td><td>Congo (Zaire)</td><td>Africa</td><td>4,700</td></tr><tr><td>8</td><td>Amur</td><td>Asia</td><td>4,444</td></tr><tr><td>9</td><td>Lena</td><td>Asia (Russia)</td><td>4,400</td></tr><tr><td>10</td><td>Mekong</td><td>Asia (SE Asia)</td><td>4,350</td></tr></table><h2>Major Indian Rivers</h2><table><tr><th>River</th><th>Origin</th><th>Flows Into</th></tr><tr><td>Ganga</td><td>Gangotri Glacier, Uttarakhand</td><td>Bay of Bengal</td></tr><tr><td>Yamuna</td><td>Yamunotri Glacier</td><td>Ganga at Prayagraj</td></tr><tr><td>Brahmaputra</td><td>Mansarovar Lake, Tibet</td><td>Bay of Bengal</td></tr><tr><td>Indus</td><td>Mansarovar Lake, Tibet</td><td>Arabian Sea</td></tr><tr><td>Godavari</td><td>Nasik, Maharashtra</td><td>Bay of Bengal</td></tr><tr><td>Krishna</td><td>Western Ghats, Maharashtra</td><td>Bay of Bengal</td></tr><tr><td>Narmada</td><td>Amarkantak, MP</td><td>Arabian Sea</td></tr></table><h2>World's Highest Mountains</h2><table><tr><th>Mountain</th><th>Range</th><th>Country</th><th>Height (m)</th></tr><tr><td>Mount Everest</td><td>Himalayas</td><td>Nepal/China</td><td>8,848.86</td></tr><tr><td>K2</td><td>Karakoram</td><td>Pakistan/China</td><td>8,611</td></tr><tr><td>Kangchenjunga</td><td>Himalayas</td><td>Nepal/India</td><td>8,586</td></tr><tr><td>Lhotse</td><td>Himalayas</td><td>Nepal/China</td><td>8,516</td></tr></table><h2>World's Oceans (Largest to Smallest)</h2><ol><li>Pacific Ocean (largest) — 165 million km²</li><li>Atlantic Ocean — 106 million km²</li><li>Indian Ocean — 70 million km²</li><li>Southern Ocean (Antarctic) — 20 million km²</li><li>Arctic Ocean (smallest) — 14 million km²</li></ol><div class='fact-box'><strong>Interesting Facts:</strong><ul><li>Pacific Ocean is larger than all land masses combined</li><li>Mariana Trench (Pacific) is the deepest point — 11,034 m deep</li><li>Mt. Everest was first summited by Sir Edmund Hillary (NZ) and Tenzing Norgay (Nepal) on May 29, 1953</li></ul></div><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to World Geography: Major Rivers, Longest Mountains and Oceans.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>विश्व की प्रमुख नदियां</h2><table><tr><th>नदी</th><th>महाद्वीप</th><th>लंबाई (km)</th></tr><tr><td>नील</td><td>अफ्रीका</td><td>6,650</td></tr><tr><td>अमेज़न</td><td>दक्षिण अमेरिका</td><td>6,400</td></tr><tr><td>यांग्त्ज़ी</td><td>एशिया</td><td>6,300</td></tr></table><h2>भारत की प्रमुख नदियां</h2><ul><li>गंगा - गंगोत्री से निकलती है</li><li>यमुना - यमुनोत्री से</li><li>ब्रह्मपुत्र - तिब्बत से</li></ul>"
    },
    {
      "id": 18,
      "slug": "mughal-empire-history",
      "title": "Mughal Empire: History, Rulers, Culture and Legacy",
      "title_hi": "मुगल साम्राज्य: इतिहास, शासक, संस्कृति और विरासत",
      "category": "competitive",
      "emoji": "🕌",
      "excerpt": "Complete guide to the Mughal Empire for UPSC, SSC and competitive exams. Learn about all Mughal emperors, their achievements and the empire's legacy.",
      "author": "Prof. Meena Joshi",
      "date": "2024-03-25",
      "readTime": 10,
      "featured": false,
      "tags": [
        "history",
        "mughal",
        "upsc",
        "medieval-india",
        "competitive"
      ],
      "content": "<h2>Introduction to Mughal Empire</h2><p>The <strong>Mughal Empire</strong> was one of the largest and most powerful empires in Indian history, ruling from 1526 to 1857. At its peak under <strong>Aurangzeb</strong>, it controlled nearly 4 million km² of territory.</p><h2>Mughal Emperors at a Glance</h2><table><tr><th>Emperor</th><th>Reign</th><th>Key Achievement</th></tr><tr><td>Babur (1st)</td><td>1526-1530</td><td>Founded Mughal Empire; Won Battle of Panipat (1526)</td></tr><tr><td>Humayun (2nd)</td><td>1530-1540, 1555-56</td><td>Lost and regained empire; Father of Akbar</td></tr><tr><td>Akbar (3rd)</td><td>1556-1605</td><td>Greatest Mughal; Din-i-Ilahi; Navratnas in court</td></tr><tr><td>Jahangir (4th)</td><td>1605-1627</td><td>Known for justice; Married Nur Jahan</td></tr><tr><td>Shah Jahan (5th)</td><td>1628-1658</td><td>Built Taj Mahal, Red Fort, Jama Masjid</td></tr><tr><td>Aurangzeb (6th)</td><td>1658-1707</td><td>Largest empire; implemented Sharia; Compiled Fatawa Alamgiri</td></tr></table><div class='highlight-box'><strong>Key Battle:</strong> First Battle of Panipat (1526) — Babur defeated Ibrahim Lodi using gunpowder and artillery for the first time in India. This established Mughal rule.</div><h2>Akbar's Navratnas (Nine Gems)</h2><div class='fact-box'>1. Birbal (Wit & Wisdom)<br>2. Tansen (Music)<br>3. Raja Todar Mal (Finance/Revenue system)<br>4. Raja Man Singh (Military)<br>5. Abul Fazl (Author of Ain-i-Akbari)<br>6. Faizi (Poet)<br>7. Mullah Do Piaza (Advisor)<br>8. Abdul Rahim Khan-i-Khana (Poet)<br>9. Fakir Aziao-Din (Mystic)</div><h2>Mughal Architecture</h2><ul><li>🕌 <strong>Taj Mahal</strong> (Agra) — Shah Jahan (1643)</li><li>🏰 <strong>Red Fort</strong> (Delhi) — Shah Jahan (1648)</li><li>🕌 <strong>Jama Masjid</strong> (Delhi) — Shah Jahan (1656)</li><li>🏰 <strong>Agra Fort</strong> — Akbar (1573)</li><li>🏙️ <strong>Fatehpur Sikri</strong> — Akbar's capital</li><li>🕌 <strong>Humayun's Tomb</strong> — First garden tomb, inspired Taj Mahal</li></ul><h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Mughal Empire: History, Rulers, Culture and Legacy.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "<h2>मुगल साम्राज्य</h2><p>मुगल साम्राज्य 1526 से 1857 तक चला। बाबर ने पानीपत की पहली लड़ाई (1526) जीतकर इसकी स्थापना की।</p><h2>प्रमुख मुगल शासक</h2><table><tr><th>शासक</th><th>उपलब्धि</th></tr><tr><td>बाबर</td><td>मुगल साम्राज्य की स्थापना</td></tr><tr><td>अकबर</td><td>सबसे महान मुगल; दीन-ए-इलाही</td></tr><tr><td>शाहजहाँ</td><td>ताज महल का निर्माण</td></tr><tr><td>औरंगजेब</td><td>सबसे बड़ा साम्राज्य</td></tr></table>"
    },
    {
      "id": 19,
      "slug": "fractions-decimals-percentages-1",
      "title": "Fractions Decimals Percentages - Complete Guide for Students",
      "title_hi": "Fractions Decimals Percentages - सम्पूर्ण गाइड",
      "category": "school",
      "emoji": "🔢",
      "excerpt": "A simple and exam-friendly guide on Fractions Decimals Percentages with key concepts, examples, and revision points.",
      "author": "Dr. Priya Sharma",
      "date": "2026-06-10",
      "readTime": 7,
      "featured": false,
      "tags": [
        "fractions",
        "decimals",
        "percentages"
      ],
      "content": "\n<h2>Introduction</h2>\n<p>Fractions  Decimals  Percentages is an important topic for students preparing for school and competitive exams. This article explains the subject clearly with examples, definitions, and quick revision notes.</p>\n<h2>Key Concepts</h2>\n<ul>\n  <li>Understand the main idea behind Fractions  Decimals  Percentages.</li>\n  <li>Learn the most important terms and examples.</li>\n  <li>Use these concepts to solve exam questions easily.</li>\n</ul>\n<h2>Important Examples</h2>\n<p>Practice questions and examples help you remember Fractions  Decimals  Percentages better. Focus on the most common points that appear in class tests and exams.</p>\n<h2>Exam Tips</h2>\n<p>Read the definitions carefully, write short answers clearly, and revise the key terms before the exam.</p>\n<h2>Summary</h2>\n<p>Fractions  Decimals  Percentages is now easier to understand after this quick guide. Remember the main points and practice regularly.</p>\n  <h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Fractions Decimals Percentages.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "\n<h2>परिचय</h2>\n<p>Fractions  Decimals  Percentages एक महत्वपूर्ण विषय है जो छात्रों के लिए परीक्षा की तैयारी में मदद करता है। यह लेख सरल भाषा में मुख्य अवधारणाओं और उदाहरणों के साथ समझाता है।</p>\n<h2>मुख्य अवधारणाएँ</h2>\n<ul>\n  <li>Fractions  Decimals  Percentages का मुख्य विचार समझें।</li>\n  <li>सबसे महत्वपूर्ण शब्दों और उदाहरणों को याद करें।</li>\n  <li>परीक्षा के प्रश्नों को हल करने के लिए इन अवधारणाओं का उपयोग करें।</li>\n</ul>\n<h2>महत्वपूर्ण उदाहरण</h2>\n<p>प्रैक्टिस प्रश्न और उदाहरण आपको Fractions  Decimals  Percentages को बेहतर तरीके से याद रखने में मदद करते हैं।</p>\n<h2>परीक्षा सुझाव</h2>\n<p>परिभाषाओं को ध्यान से पढ़ें, उत्तर स्पष्ट लिखें और परीक्षा से पहले मुख्य बिंदुओं को दोहराएँ।</p>\n<h2>सारांश</h2>\n<p>यह गाइड Fractions  Decimals  Percentages को समझना आसान बनाती है। मुख्य बिंदुओं को याद रखें और नियमित अभ्यास करें।</p>\n  "
    },
    {
      "id": 20,
      "slug": "reasoning-tricks-and-shortcuts",
      "title": "Reasoning Tricks and Shortcuts - Complete Guide for Students",
      "title_hi": "Reasoning Tricks and Shortcuts - सम्पूर्ण गाइड",
      "category": "competitive",
      "emoji": "💻",
      "excerpt": "A simple and exam-friendly guide on Reasoning Tricks and Shortcuts with key concepts, examples, and revision points.",
      "author": "Saurabh Pandey",
      "date": "2026-06-10",
      "readTime": 11,
      "featured": false,
      "tags": [
        "reasoning",
        "tricks",
        "and",
        "shortcuts"
      ],
      "content": "\n<h2>Introduction</h2>\n<p>Reasoning  Tricks and  Shortcuts is an important topic for students preparing for school and competitive exams. This article explains the subject clearly with examples, definitions, and quick revision notes.</p>\n<h2>Key Concepts</h2>\n<ul>\n  <li>Understand the main idea behind Reasoning  Tricks and  Shortcuts.</li>\n  <li>Learn the most important terms and examples.</li>\n  <li>Use these concepts to solve exam questions easily.</li>\n</ul>\n<h2>Important Examples</h2>\n<p>Practice questions and examples help you remember Reasoning  Tricks and  Shortcuts better. Focus on the most common points that appear in class tests and exams.</p>\n<h2>Exam Tips</h2>\n<p>Read the definitions carefully, write short answers clearly, and revise the key terms before the exam.</p>\n<h2>Summary</h2>\n<p>Reasoning  Tricks and  Shortcuts is now easier to understand after this quick guide. Remember the main points and practice regularly.</p>\n  <h2>Quick Revision Notes</h2><ul><li>Read the definition and write it once in your own words.</li><li>Make a small table of key facts, formulas, dates, or examples related to Reasoning Tricks and Shortcuts.</li><li>Revise the topic after 24 hours and again before the exam.</li></ul><h2>Common Mistakes to Avoid</h2><ul><li>Do not memorize only headings; understand the reason behind every point.</li><li>Do not mix similar terms, dates, examples, or formulas.</li><li>Do not skip practice questions after reading the explanation.</li></ul><h2>Practice Questions</h2><ol><li>Write a short note on the main idea of this topic.</li><li>List three important facts that can be asked in exams.</li><li>Explain one example in simple language.</li><li>Create five one-line revision points from this article.</li></ol><h2>Frequently Asked Questions</h2><h3>Is this topic important for exams?</h3><p>Yes. This topic is useful for school tests, revision, and competitive exam general awareness depending on the syllabus.</p><h3>How should I revise it quickly?</h3><p>Start with the summary, then revise the table or bullet points, and finally solve two or three practice questions.</p>",
      "content_hi": "\n<h2>परिचय</h2>\n<p>Reasoning  Tricks and  Shortcuts एक महत्वपूर्ण विषय है जो छात्रों के लिए परीक्षा की तैयारी में मदद करता है। यह लेख सरल भाषा में मुख्य अवधारणाओं और उदाहरणों के साथ समझाता है।</p>\n<h2>मुख्य अवधारणाएँ</h2>\n<ul>\n  <li>Reasoning  Tricks and  Shortcuts का मुख्य विचार समझें।</li>\n  <li>सबसे महत्वपूर्ण शब्दों और उदाहरणों को याद करें।</li>\n  <li>परीक्षा के प्रश्नों को हल करने के लिए इन अवधारणाओं का उपयोग करें।</li>\n</ul>\n<h2>महत्वपूर्ण उदाहरण</h2>\n<p>प्रैक्टिस प्रश्न और उदाहरण आपको Reasoning  Tricks and  Shortcuts को बेहतर तरीके से याद रखने में मदद करते हैं।</p>\n<h2>परीक्षा सुझाव</h2>\n<p>परिभाषाओं को ध्यान से पढ़ें, उत्तर स्पष्ट लिखें और परीक्षा से पहले मुख्य बिंदुओं को दोहराएँ।</p>\n<h2>सारांश</h2>\n<p>यह गाइड Reasoning  Tricks and  Shortcuts को समझना आसान बनाती है। मुख्य बिंदुओं को याद रखें और नियमित अभ्यास करें।</p>\n  "
    }
  ],
  "categories": [
    {
      "id": "school",
      "name": "School Education",
      "name_hi": "स्कूल शिक्षा",
      "emoji": "🎒",
      "description": "Class 6-12 subjects including Science, Math, History, English",
      "color": "#6366f1",
      "count": 8
    },
    {
      "id": "competitive",
      "name": "Competitive Exams",
      "name_hi": "प्रतियोगी परीक्षाएं",
      "emoji": "🏆",
      "description": "SSC, UPSC, Banking, Railway and other competitive exam prep",
      "color": "#f59e0b",
      "count": 7
    },
    {
      "id": "gk",
      "name": "General Knowledge",
      "name_hi": "सामान्य ज्ञान",
      "emoji": "🌍",
      "description": "India, World, Science, Sports, History general knowledge",
      "color": "#10b981",
      "count": 5
    }
  ]
};
